### PR TITLE
corrected file sharing exception and limit checklist appending

### PR DESCRIPTION
**Pull request by aa3m**
- changed print routine to print only puzzle or answer sheets ShowPuzzle.cs buildPrintString() 
- along with a serial number to match them using makeSerialNumber()
- Corrected an exception error when saving back to the original loaded filename by adding 
- reader.Close(); to the CreateWordFind.cs file (line 131)  3/15/2024  de AA3M
- Added _checklist.Clear(); to CreateWordFind.cs file (line 38 ) to fix checkbox settings list upon saving

### CODE REVIEW

**Comment by caraconrad** [comment]
Looks great, thanks for contributing!

**Comment by aa3m** [comment]
Cara,I was very impressed with your Wordfind-Generator. All your effort hasn’t gone to waste. Somebody out there appreciated it. Me ;)Best regards.JohnI forgot to add the “instruction” sheet. Preferably a “Help” button?The core operation is the same except that whatever you see in the Puzzle View ( after hitting GENERATE PUZZLE button.  ) is what gets printed when you click the PRINT button. You may print as many copies of the puzzle with the same serial number that matches the answer sheet. You then TOGGLE to the answer view and print the answer sheet. A new random serial number is generated every time the GENERATE PUZZLE button is pressed. If different puzzles are required.You press GENERATE PUZZLE and a new serial number is assigned to the puzzle/answer sheet in PUZZLE VIEW.Thank You again for your very talented Wordfind. On Apr 2, 2024, at 13:49, caraconrad ***@***.***> wrote:﻿
Looks great, thanks for contributing!

**Comment by caraconrad** [comment]
Thanks! I originally wrote this like 10 years ago for a school project and thought it would be neat to share it. Never really expected anyone to find it or care about it let alone want to contribute so this was cool to see!

I think something I want to do is to flesh out the readme.md to include some instructions and explain some distinctions between some functionality (save/load vs export vs print for instance) since it's simply easier and cleaner to provide instructions here rather than in the program. Then I'll make a help>about section in the program that says some general information about the program and provide a link back to the repo/readme for the instructions.

There's a few other things I want to add and some cleanup I'd like to do too so keep an eye out cause there will probably be an update soon!

**Comment by aa3m** [comment]
Great!Looking forward to those additions.I like your idea on the instructions/readme file.Much easier to maintain.Back story on my end.Our youngest is 32 years old. Back in 1993 I modified an existing Wordfind ( by Pehr Anderson ?) doing basically the same thing by adding the serial number. It was cumbersome to use and required a separate text file that contained the words to build the puzzle and the dimensions. Now that we have grandkids I thought they might get a kick out of it and decided to port it to a newer compiler. That’s when I found Microsoft Visual Studio and attempted to use it to build the single C source file. I was doing pretty good rewriting about 80% of it but hit a brick wall at some point. Then I had the epiphany. Someone else must have done it already. And searched. That’s when I found yours. There are others. But I liked your setup and it was very easy to use.I’m more of a hobbyist when it comes to programming. I find it interesting. Thank goodness my life didn’t / doesn’t depend on it. There’s always something to learn along the way. I was comfortable with directories and subdirectories. Then they had to do this folders and sub-folders thing. This time around I was looking at file streams instead of file handles. Good Grief as Charlie Brown would say.I now have a useful tool to play with the kids. I even gave a copy to the principal of the local grade school where I once taught an after hours electronics course. The ability to adjust the randomization of the word layout is perfect for any grade level. Left/right, top/down is handy for the lower grades. One of my son-in-laws ( I have four of them ) is an accomplished coder. He’s the one who turned me on to GitHub. To be honest I know that I could not have accomplished what I did without it. The ability to track the changes ( and revert ) alone is worth it. My apologies for taking up so much of your time. You made a bunch of folks happy with that orphaned project of yours. I’m so glad to be able to put it to good use.Best Regards On Apr 3, 2024, at 09:56, caraconrad ***@***.***> wrote:﻿
Thanks! I originall wrote this like 10 years ago for a school project and thought it would be neat to share it. Never really expected anyone to find it or care about it let alone want to contribute so this was cool to see!
I think something I want to do is to flesh out the readme.md to include some instructions and explain some distinctions between some functionality (save/load vs export vs print for instance) since it's simply easier and cleaner to provide instructions here rather than in the program. Then I'll make a help>about section in the program that says some general information about the program and provide a link back to the repo/readme for the instructions.
There's a few other things I want to add and some cleanup I'd like to do too so keep an eye out cause there will probably be an update soon!

**Comment by caraconrad** [comment]
Thank you for sharing! It makes my day to know you guys are using the program and that it was useful after all! It encourages me to work more on the project and to try my hand at some new projects as well.

**Comment by aa3m** [comment]
Hello Cara,You have been busy.I’m thrilled to see that my interest in your program has renewed your zeal for your own creation.I believe my sights were set a bit lower than yours.My vision for this program was targeted to a lower level usage ( adolescents ) audience.Bear in mind that your level of expertise in creating the actual puzzle creation is way beyond my current level of knowledge.I honestly don’t think I’ll live long enough to digest and comprehend it fully on my own. For that alone you should be proud of your achievement.I checked out your current changes and I think maybe I picked up on your intention to use the random generator to seed the actual puzzle generation in addition to displaying it.I did not merge your project at this time. I loaded your current changes as a stand alone project so I could see the results without committing to it.Any differences I made since you saw my commit a few weeks ago are strictly cosmetic adjustments. I added a button display change to change the readout when you are in the puzzle view to “show answers” or “show puzzle”. Also some minor mouseover prompting, but that’s it.Regarding my lower level audience. I limited the serial number range to three digits for simplicity. A teacher having to read a string long enough to be a license plate number would be somewhat confusing for her/him.Yes the new longer number would be quite unique. But the possibility of an identical chance is very small with the three digits. It’s a risk I was willing to take.I didn’t want to “request” any work on your part regarding a wish-list for some changes to the program. ( it is a fun project, no? ) When it becomes work it loses its luster.The program now as it stands is functional enough for me. What I would have liked to see would be to add another print button which would automatically print the puzzle AND answer sheet with a single press. That would add functionality and also simplify at the same time.Right now it requires a print puzzle, toggle ( show / answers button ) and then print the answers. I was stumped trying to get a form-feed between the exported sheets.Spun my wheels a bit and eventually gave up on it when I first touched this project. I see that you added the serial number to that export function. The formfeed was necessary for me in that the two views over-ran a single sheet leaving a partial view on one sheet and the other part on the second sheet. I was using Notepad to view the exported.txt file and print it.Spring is upon us and my “funtime” is being diverted to other obligations. Cutting the lawn, gardening, outside maintenance chores.How I long for the winter months….I hope this summer finds you in good health and thank you again for your encouragement.Best RegardsJohnOn Apr 2, 2024, at 13:49, caraconrad ***@***.***> wrote:﻿
Looks great, thanks for contributing!

**Comment by caraconrad** [comment]
Hello!

So my idea for expanding the functionality of the serial number was purely for the idea that it would be neat if you can generate the same puzzle by entering the serial number of a puzzle that was previously generated. So if you had a puzzle printed and know the word list and the serial number but didn't export then it would be possible to to generate the same puzzle and print more of them just from reentering the word list and serial number. I went with a larger number just because that's what the random() method takes, but yeah there's no reason to use the whole range and I could easily dial it back to 3 digits! Could also just scrap the idea entirely and go back to how it was, it was just a thought I had and wanted to see if I could get it working! And I can take the number back out of export if that works better too.

I can definitely take a look at the printing idea sometime, it's been a while since I looked at it. I think it uses some built in print routine that isn't very good. Like I noticed it won't print past one page so if you make a puzzle too big it just gives up after a page. But I'll take a look around, if it's not possible with whatever it's using now there's probably a library someone made at some point.

If you have an idea for the project but unsure how to implement it like the print idea you can always add a feature request! You can do it by going to the Issues tab and creating a new issue. I don't mind working on this once in a while !

**Comment by aa3m** [comment]
Well the entering the serial number idea can save on paper. If you discovered a printer problem during the hard copy process you can print another.I just tried the enter the serial number function and it works well. You are adventurous as I am with regards to trying different things and see the results just for the experience. I went a little further and removed one of the words in the list. I entered the copied serial number and noticed that the puzzle is different.Not 100% on how to avoid that situation. You can’t stop the user from cleverly coming up with some goofy way of using the software.I first thought to save the serial number with the “saved puzzle”. But that would only work while that list was intact. If they add or delete from it, the puzzle has changed even with the same serial number. What did I expect ? :)If changing the word list caused the manual serial number to clear, then I think we’re back to square one. As for the serial number on the export….It doesn’t matter. Until the printing issue is resolved ( print puzzle on one sheet, and print the answers on sheet two, it’s not a problem.The export output in my opinion should be printable from a text editor. But getting the formfeed control character to imbed itself within that generated text was the stumper for me.The export can appear sequential on the display, but printing it should have the formfeed. While you’re having fun playing with the export, maybe also include the word list as they appear on the printed puzzle / answer sheets. I know you can see them in the answers, but it would be helpful. Only need to print them once with the Puzzle sheet in the export. The second sheet, answers would be redundant.I haven’t ran into the issue of a giantic puzzle that exceeds the printable area.Can that be addressed by limiting the number of rows/ columns?As for the additional button to print both sheets ( puzzle and answers). Maybe a call to two separate print streams. Call puzzle print, let it close, call answer print, let it close.The print routine is “clean” and simple as it stands. You print to your default printer whatever it may be. Most folks have one printer. Yes it would be nice to get the print dialog window and choose your printer. But the users I encounter are happier with less options. As soon as you give them more than one choice it seems insurmountable to them.You can download my recent code and look at the “toggle” button operation on the puzzle view page. I wouldn’t merge it. Just  download it as a new project ( I renamed your current version as “_2” and saved it locally. You can then run it without debug and try it out.Much easier than trying to pick through a bunch of code in a “blender” if you accidentally merged the two projects. Good to know you’re still out there.I’ll try to include that “print request” under feature requests on GitHub. Looks more official. ;)Best RegardsJohnOn Apr 28, 2024, at 11:18, caraconrad ***@***.***> wrote:﻿Hello!So my idea for expanding the functionality of the serial number was purely for the idea that it would be neat if you can generate the same puzzle by entering the serial number of a puzzle that was previously generated. So if you had a puzzle printed and know the word list and the serial number but didn't export then it would be possible to to generate the same puzzle and print more of them just from reentering the word list and serial number. I went with a larger number just because that's what the random() method takes, but yeah there's no reason to use the whole range and I could easily dial it back to 3 digits! Could also just scrap the idea entirely and go back to how it was, it was just a thought I had and wanted to see if I could get it working! And I can take the number back out of export if that works better too.I can definitely take a look at the printing idea sometime, it's been a while since I looked at it. I think it uses some built in print routine that isn't very good. Like I noticed it won't print past one page so if you make a puzzle too big it just gives up after a page. But I'll take a look around, if it's not possible with whatever it's using now there's probably a library someone made at some point.If you have an idea for the project but unsure how to implement it like the print idea you can always add a feature request! You can do it by going to the Issues tab and creating a new issue. I don't mind working on this once in a while !—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Pull request merged**
